### ISSUE TITLE
Senderstatus am APRS-Symbol erkennbar machen

### ISSUE THREAD

**Issue by pe2kmv** [DecentralizedAmateurPagingNetwork/DAPNETAPRS#4]
aprs.fi hat nicht die Möglichkeit Objekte zu löschen / killen. Daher sind offline Sender nicht am Symbol erkennbar.

Vorschläge:
- es bleibt so wie es ist, Senderstatus ist nur über Kommentartext erkennbar;
- online Sender haben 'P' als Overlay-Symbol, offline Sender ein 'X' auf dem grünen Digi-Symbol;
- online Sender haben das grüne Digi-Symbol, offline Sender ein rotes Dreieck (\n) aber beiden haben ein 'P' als Overlay.

**Comment by dh3wr** [comment]
Ich würde Option 3 bevorzugen. Option 2 wäre auch ok.
